# Generated by Django 5.0.9 on 2024-10-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['advanced', 'pro', 'basic'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
