# Generated by Django 5.0.9 on 2024-10-07 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_usersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='subscirption',
            new_name='subscription',
        ),
    ]
