# Generated by Django 5.0.9 on 2024-10-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_rename_subscirption_usersubscription_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
