# Generated by Django 5.0.9 on 2024-10-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptions_stripe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=10)),
                ('interval', models.CharField(choices=[('month', 'MONTHLY'), ('year', 'YEARLY')], default='month', max_length=120)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptions')),
            ],
        ),
    ]
