# Generated by Django 5.0.9 on 2024-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscriptionsprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsprice',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionsprice',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
