# Generated by Django 5.0.9 on 2024-10-14 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscriptionsprice_featured_subscriptionsprice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsprice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionsprice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscriptionsprice',
            name='featured',
            field=models.BooleanField(default=True, help_text='featured on Django pricing page'),
        ),
        migrations.AlterField(
            model_name='subscriptionsprice',
            name='order',
            field=models.IntegerField(default=-1, help_text='Ordering on django pricing page'),
        ),
    ]
