# Generated by Django 5.0.9 on 2024-10-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscriptionsprice_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionsprice',
            options={'ordering': ['order', 'featured', '-updated']},
        ),
    ]
